replicaCount: 1

image:
  repository: nginx
  tag: "1.25"

service:
  type: LoadBalancer
  port: 8085
  annotations:
    lbipam.cilium.io/sharing-key: "apps"
    lbipam.cilium.io/sharing-cross-namespace: "*"

ingress:
  enabled: false

extraArgs:
  - /bin/sh
  - -c
  - echo 'Hello from C via HELM!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
